; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26129.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\srjiwtod\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
